version: '3.9'

services:
  mariadb:
    image: mariadb:11
    container_name: blue-quirk-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: blue-quirk-db
      MARIADB_USER: blue-quirk-user
      MARIADB_PASSWORD: "blue-quirk-pass-!"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: blue-quirk-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass

volumes:
  mariadb_data:
