version: "3.8"
services:

  blue-quirk-backend:
   image: bq/blue-quirk-backend:0.0.1-SNAPSHOT
   container_name: blue-quirk-backend
   depends_on:
     keycloak-server:
       condition: service_healthy
     identity-service:
       condition: service_healthy
   environment:
    SPRING_PROFILES_ACTIVE: docker
   ports:
    - "8080:8080"  # map container port 8080 to host
   networks:
    - base
   volumes:
    - ./uploads:/app/uploads

