package shop.bluequirk.blue_quirk_backend.review.entity;

import java.time.Instant;

import jakarta.persistence.*;

/**
 * A single-use, unguessable token that authorizes one review submission for a
 * specific delivered order. Generated by {@code ReviewRequestScheduler} once an
 * order has been {@code DELIVERED} for the configured delay, and delivered to the
 * customer via the review-request email (channel-agnostic by design).
 *
 * <p>This is the backbone of the "no fake reviews" guarantee on the submission
 * side: there is <b>no open/anonymous review form</b>. To post a review a customer
 * must hold a valid, unexpired, unused token — which only a real delivered order
 * yields — and the product they review must actually be on that order, which makes
 * every such review a genuine <i>Verified purchase</i>.
 */
@Entity
@Table(name = "review_request_tokens", indexes = {
        @Index(name = "idx_review_token", columnList = "token", unique = true),
        @Index(name = "idx_review_token_order", columnList = "order_id")
})
public class ReviewRequestToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** URL-safe random secret (SecureRandom). Unique. */
    @Column(nullable = false, unique = true, length = 64)
    private String token;

    /** The delivered order this token unlocks reviews for (snapshot id — no FK). */
    @Column(name = "order_id", nullable = false)
    private Long orderId;

    /** After this instant the token no longer works. */
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    /** Set the moment the token is redeemed — makes it single-use. Null = unused. */
    @Column(name = "used_at")
    private Instant usedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    void onCreate() {
        if (this.createdAt == null) this.createdAt = Instant.now();
    }

    public ReviewRequestToken() {}

    public ReviewRequestToken(String token, Long orderId, Instant expiresAt) {
        this.token = token;
        this.orderId = orderId;
        this.expiresAt = expiresAt;
    }

    public boolean isRedeemable() {
        return usedAt == null && expiresAt != null && expiresAt.isAfter(Instant.now());
    }

    // --- Getters & setters ---
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }

    public Long getOrderId() { return orderId; }
    public void setOrderId(Long orderId) { this.orderId = orderId; }

    public Instant getExpiresAt() { return expiresAt; }
    public void setExpiresAt(Instant expiresAt) { this.expiresAt = expiresAt; }

    public Instant getUsedAt() { return usedAt; }
    public void setUsedAt(Instant usedAt) { this.usedAt = usedAt; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
